apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: crypto-scan-oci-ta
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: konflux
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    The crypto-scan task uses [rh-crypto-scan](https://gitlab.cee.redhat.com/security-guild/crypto-scanning/rh-crypto-scanner) tool to perform Static Code Analysis in order to detect crypto assets being used.
    rh-crypto-scan is a tool under development that reports crypto algorithms in CycloneDX format.
  params:
    - name: CACHI2_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the prefetched dependencies.
      type: string
      default: ""
    - name: PROJECT_NAME
      description: Name of the scanned project, used to find path exclusions.
        By default, the Konflux component name will be used.
      type: string
      default: ""
    - name: RECORD_EXCLUDED
      description: |
        Whether to record the excluded findings (default to false).
        If `true`, the excluded findings will be stored in `excluded-findings.json`.
      type: string
      default: "false"
    - name: SOURCE_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the application source code.
      type: string
    - name: TARGET_DIRS
      description: Target directories in component's source code. Multiple
        values should be separated with commas.
      type: string
      default: .
    - name: caTrustConfigMapKey
      description: The name of the key in the ConfigMap that contains the
        CA bundle data.
      type: string
      default: ca-bundle.crt
    - name: caTrustConfigMapName
      description: The name of the ConfigMap to read CA bundle data from.
      type: string
      default: trusted-ca
    - name: image-digest
      description: Image digest to report findings for.
      type: string
      default: ""
    - name: image-url
      description: Image URL.
      type: string
      default: ""
    - name: SKIP_SBOM_GENERATION
      description: Skip SBOM-related operations. This will likely cause EC policies to fail if enabled
      type: string
      default: "false"
  results:
    - name: TEST_OUTPUT
      description: Tekton task test output.
  volumes:
    - name: trusted-ca
      configMap:
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        name: $(params.caTrustConfigMapName)
        optional: true
    - name: workdir
      emptyDir: {}
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: use-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:4689f88dd253bd1feebf57f1a76a5a751880f739000719cd662bbdc76990a7fd
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/var/workdir/source
        - $(params.CACHI2_ARTIFACT)=/var/workdir/cachi2
      volumeMounts:
        - mountPath: /etc/pki/tls/certs/ca-custom-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
    - name: rh-crypto-scan
      image: quay.io/redhat-user-workloads/exd-sp-guild-securit-tenant/rh-crypto-scanner-image:on-pr-21af362976ef7bd009a4ae467bb05b5ee07dc6cd
      workingDir: /var/workdir/source
      env:
        - name: PROJECT_NAME
          value: $(params.PROJECT_NAME)
        - name: RECORD_EXCLUDED
          value: $(params.RECORD_EXCLUDED)
        - name: TARGET_DIRS
          value: $(params.TARGET_DIRS)
        - name: COMPONENT_LABEL
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['appstudio.openshift.io/component']
        - name: BUILD_PLR_LOG_URL
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['pipelinesascode.tekton.dev/log-url']
      script: |

        if [ "${SKIP_SBOM_GENERATION}" = "true" ]; then
          echo "Skipping SBOM generation"
          exit 0
        fi

        PACKAGE_VERSION=$(rh-crypto-scanner --version)
        echo "Using rh-crypto-scanner version: ${PACKAGE_VERSION}"

        SOURCE_CODE_DIR="/var/workdir/source"
        

        # generate full path for each dirname separated by comma
        declare -a ALL_TARGETS
        IFS="," read -ra TARGET_ARRAY <<<"$TARGET_DIRS"
        for d in "${TARGET_ARRAY[@]}"; do
          potential_path="${SOURCE_CODE_DIR}/${d}"

          resolved_path=$(realpath -m "$potential_path")

          # ensure resolved path is still within SOURCE_CODE_DIR
          if [[ "$resolved_path" == "$SOURCE_CODE_DIR"* ]]; then
            ALL_TARGETS+=("$resolved_path")
          else
            echo "Error: path traversal attempt, '$potential_path' is outside '$SOURCE_CODE_DIR'"
            exit 1
          fi
        done

        echo "Running rh-crypto-scanner on the source directory"
        rh-crypto-scanner ${ALL_TARGETS[@]}

        note="Task $(context.task.name) completed successfully."
      computeResources:
        limits:
          cpu: "8"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 4Gi
    - name: upload
      image: quay.io/konflux-ci/oras:latest@sha256:1beeecce012c99794568f74265c065839f9703d28306a8430b667f639343a98b
      workingDir: /var/workdir/source
      volumeMounts:
        - mountPath: /etc/pki/tls/certs/ca-custom-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
      env:
        - name: IMAGE_URL
          value: $(params.image-url)
        - name: IMAGE_DIGEST
          value: $(params.image-digest)
      script: |
        #!/usr/bin/env bash
        set -e

        if [ -z "${IMAGE_URL}" ] || [ -z "${IMAGE_DIGEST}" ]; then
          echo 'No image-url or image-digest param provided. Skipping upload.'
          exit 0
        fi

        UPLOAD_FILES="cbom.json report.json"

        for UPLOAD_FILE in ${UPLOAD_FILES}; do
          if [ ! -f "${UPLOAD_FILE}" ]; then
            echo "No ${UPLOAD_FILE} exists. Skipping upload."
            continue
          fi

          # Determine the media type based on the file extension
          if [[ "${UPLOAD_FILE}" == *.json ]]; then
            MEDIA_TYPE="application/json"
          else
            MEDIA_TYPE="application/sarif+json"
          fi

          echo "Selecting auth"
          select-oci-auth "$IMAGE_URL" >"$HOME/auth.json"
          echo "Attaching to ${IMAGE_URL}"
          if ! retry oras attach --no-tty --registry-config "$HOME/auth.json" --artifact-type "${MEDIA_TYPE}" "${IMAGE_URL}@${IMAGE_DIGEST}" "${UPLOAD_FILE}:${MEDIA_TYPE}"; then
            echo "Failed to attach ${UPLOAD_FILE} to ${IMAGE_URL}"
            exit 1
          fi
        done
      computeResources:
        limits:
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 256Mi
